name: CI/CD Dev Branch Deployment

on:
  workflow_dispatch:

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment:
      name: dev   # 👈 Requires approval (set in repo Settings → Environments)
      url: https://your-dev-app.example.com   # optional

    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Deploy dev branch to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_KEY }}
          script: |
            mkdir -p /home/ubuntu/dev_app
            cd /home/ubuntu/dev_app

            if [ ! -d .git ]; then
              git init
              git remote add origin https://github.com/${{ github.repository }}.git || true
            fi
            git fetch origin dev
            git checkout dev || git checkout -b dev
            git pull origin dev

            if ! command -v node &> /dev/null; then
              curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
              sudo apt-get update -y
              sudo apt-get install -y nodejs
            fi

            npm install
            pm2 delete my-aws-cicd-dev || true
            pm2 start ecosystem.config.js --name my-aws-cicd-dev
